"""phase 2a: transaction ingestion columns and service role

Revision ID: 31b82a0dc987
Revises: 67664cad4b89
Create Date: 2026-08-26 22:44:48.573537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b82a0dc987'
down_revision: Union[str, Sequence[str], None] = '67664cad4b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # [Hand-adjusted after autogenerate] Postgres's native `userrole` enum
    # type needs an explicit ALTER TYPE to gain the new 'service' value
    # (docs/SECURITY_AND_GOVERNANCE.md §3, Phase 2A) - autogenerate against
    # SQLite (this repo's portable diff baseline, see app/db/session.py's
    # module docstring) can't detect this, since SQLite has no native enum
    # type to diff. Guarded to Postgres only; SQLite's `users.role` column
    # already reflects the current Python UserRole definition whenever its
    # schema is freshly created via Base.metadata.create_all (tests), so
    # nothing is needed there.
    #
    # PostgreSQL note: ALTER TYPE ... ADD VALUE cannot run in the same
    # transaction as a statement that *uses* the new value - this migration
    # only adds the value and never references 'service' itself, so it's
    # safe inside Alembic's default per-migration transaction.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'service'")

    # ### commands auto generated by Alembic - explicit constraint names
    # substituted for the autogenerated `None`, and wrapped in batch mode
    # because SQLite (this repo's portable local/test dialect - see
    # app/db/session.py) cannot ALTER TABLE to add a constraint directly;
    # batch mode's copy-and-move strategy is a no-op passthrough to plain
    # ALTER on Postgres, so this is identical DDL there. ###
    op.add_column('transactions', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    op.add_column('transactions', sa.Column('exit_channel_id', sa.String(length=36), nullable=True))
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.create_unique_constraint('uq_transactions_idempotency_key', ['idempotency_key'])
        batch_op.create_foreign_key(
            'fk_transactions_exit_channel_id', 'exit_channels',
            ['exit_channel_id'], ['channel_id'],
        )


def downgrade() -> None:
    """Downgrade schema.

    Deliberately does not attempt to remove 'service' from the Postgres
    enum type - PostgreSQL has no `ALTER TYPE ... DROP VALUE` at all, only
    a full type rebuild (create new type, migrate every column, drop old
    type), which is real work disproportionate to a downgrade path this
    codebase does not exercise in its normal lifecycle (see this migration's
    own predecessor's downgrade() docstring on the same point).
    """
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.drop_constraint('fk_transactions_exit_channel_id', type_='foreignkey')
        batch_op.drop_constraint('uq_transactions_idempotency_key', type_='unique')
        batch_op.drop_column('exit_channel_id')
        batch_op.drop_column('idempotency_key')
