"""widen audit_events.subject_id to 64 chars for ring_id

Revision ID: 4e66e0da0ea0
Revises: e274d311fa2e
Create Date: 2026-08-26 20:14:56.461987

Phase 2B foundation fix. Every other subject_id in this system is a
36-char UUID, but a ring's subject_id is its deterministic SHA-256
ring_id (app/graph/ring_service.py::compute_ring_id, 64 hex chars) -
VARCHAR(36) silently truncated it on real PostgreSQL, raising
StringDataRightTruncation mid-`run_ring_detection`, aborting before
`db.commit()` while the ring's already-committed Neo4j write survived.

Hand-trimmed from the raw `alembic revision --autogenerate` output: the
autogenerated diff also proposed dropping every PostGIS/tiger/topology
extension table (they live outside SQLAlchemy's Base.metadata, so
autogenerate wrongly reads them as "should not exist"). None of that
belongs here - this migration touches exactly one column.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e66e0da0ea0'
down_revision: Union[str, Sequence[str], None] = 'e274d311fa2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        'audit_events', 'subject_id',
        existing_type=sa.String(length=36),
        type_=sa.String(length=64),
        existing_nullable=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column(
        'audit_events', 'subject_id',
        existing_type=sa.String(length=64),
        type_=sa.String(length=36),
        existing_nullable=True,
    )
