"""initial schema

Revision ID: 67664cad4b89
Revises: 
Create Date: 2026-08-26 17:28:48.316919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67664cad4b89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # [Added post-hoc, Phase 1 closure] docs/ARCHITECTURE.md §8 names
    # PostgreSQL+PostGIS as the locked target. The `postgis/postgis` Docker
    # image only auto-enables the extension on the *database it creates at
    # first container init* (POSTGRES_DB) - a database created any other
    # way (a fresh DB in the same container, a managed Postgres instance in
    # production that already has the PostGIS binary installed) does not
    # get it automatically. This migration is what makes a bare `CREATE
    # DATABASE` + `alembic upgrade head` sufficient on its own, with no
    # dependency on which image or init path created the database -
    # confirmed necessary after a manual DROP/CREATE DATABASE during Docker
    # verification silently lost the extension on the working database.
    #
    # Guarded to Postgres only: this migration also runs against SQLite
    # (app/db/session.py's documented Docker-less fallback), which has no
    # CREATE EXTENSION statement at all.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('bank_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ifsc_prefix', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('bank_id')
    )
    op.create_table('exit_channels',
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('channel_type', sa.Enum('atm_cash', 'crypto_p2p', 'ecommerce_merchant', name='exitchanneltype'), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=False),
    sa.Column('geo_lat', sa.Float(), nullable=False),
    sa.Column('geo_lon', sa.Float(), nullable=False),
    sa.Column('h3_cell', sa.String(length=20), nullable=False),
    sa.Column('channel_attributes', sa.JSON(), nullable=False),
    sa.Column('intervention_action_type', sa.Enum('physical_team_deployment', 'exchange_freeze_request', 'merchant_hold_request', name='interventionactiontype'), nullable=False),
    sa.Column('historical_incident_count', sa.Integer(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_index(op.f('ix_exit_channels_h3_cell'), 'exit_channels', ['h3_cell'], unique=False)
    op.create_table('jurisdictions',
    sa.Column('jurisdiction_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('jurisdiction_id')
    )
    op.create_table('model_registry',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.Enum('ring_detector', 'corridor_predictor', 'location_scorer', 'time_window_model', name='modelstage'), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('accounts',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('account_hash', sa.String(length=64), nullable=False),
    sa.Column('bank_id', sa.String(length=36), nullable=True),
    sa.Column('branch_lat', sa.Float(), nullable=True),
    sa.Column('branch_lon', sa.Float(), nullable=True),
    sa.Column('kyc_risk_tier', sa.Enum('low', 'medium', 'high', name='kycrisktier'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('ring_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.bank_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_accounts_account_hash'), 'accounts', ['account_hash'], unique=True)
    op.create_index(op.f('ix_accounts_ring_id'), 'accounts', ['ring_id'], unique=False)
    op.create_table('h3_cell_jurisdiction',
    sa.Column('h3_cell', sa.String(length=20), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.jurisdiction_id'], ),
    sa.PrimaryKeyConstraint('h3_cell')
    )
    op.create_table('response_units',
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('available', 'deployed', 'offline', name='responseunitstatus'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.jurisdiction_id'], ),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('citizen_portal', 'investigator', 'supervisor', 'bank_liaison', 'auditor', 'admin', name='userrole'), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=36), nullable=True),
    sa.Column('bank_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.bank_id'], ),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.jurisdiction_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('this_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_events_seq_no'), 'audit_events', ['seq_no'], unique=True)
    op.create_table('complaints',
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('incident_reference', sa.String(length=32), nullable=False),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('incident_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fraud_type', sa.Enum('upi_fraud', 'phishing', 'investment_scam', 'loan_app_fraud', 'other', name='fraudtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('location_text', sa.String(length=500), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('institution_type', sa.Enum('bank', 'wallet', 'merchant', 'exchange', 'other', name='institutiontype'), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_notes', sa.JSON(), nullable=False),
    sa.Column('victim_account_id', sa.String(length=36), nullable=True),
    sa.Column('jurisdiction_id', sa.String(length=36), nullable=True),
    sa.Column('jurisdiction_hint', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('new', 'graph_building', 'predicted', 'action_recommended', 'approved', 'rejected', 'closed', name='complaintstatus'), nullable=False),
    sa.Column('assigned_investigator_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.Enum('own_intake_form', 'ncrp_feed_future', name='complaintsource'), nullable=False),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['assigned_investigator_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.jurisdiction_id'], ),
    sa.ForeignKeyConstraint(['victim_account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('complaint_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_complaints_incident_reference'), 'complaints', ['incident_reference'], unique=True)
    op.create_table('linked_entities',
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.Enum('device', 'phone', 'address_cluster', 'ip', 'vpa', 'email', name='linkedentitytype'), nullable=False),
    sa.Column('entity_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index(op.f('ix_linked_entities_entity_hash'), 'linked_entities', ['entity_hash'], unique=False)
    op.create_table('feature_snapshots',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('feature_vector', sa.JSON(), nullable=False),
    sa.Column('label', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('predictions',
    sa.Column('prediction_id', sa.String(length=36), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version_ring', sa.String(length=64), nullable=True),
    sa.Column('model_version_corridor', sa.String(length=64), nullable=True),
    sa.Column('model_version_location', sa.String(length=64), nullable=True),
    sa.Column('model_version_time', sa.String(length=64), nullable=True),
    sa.Column('ranked_locations', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('feature_snapshot', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_table('transactions',
    sa.Column('txn_id', sa.String(length=36), nullable=False),
    sa.Column('from_account_id', sa.String(length=36), nullable=False),
    sa.Column('to_account_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('channel', sa.Enum('upi', 'imps', 'neft', 'card', 'cash_withdrawal', name='transactionchannel'), nullable=False),
    sa.Column('hop_index', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('txn_id')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.Enum('dashboard', 'sms_sim', 'email_sim', 'bank_webhook_sim', 'i4c_webhook_sim', 'exchange_webhook_sim', 'merchant_webhook_sim', name='alertchannel'), nullable=False),
    sa.Column('recipient_ref', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('recommended_deployments',
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=False),
    sa.Column('optimizer_mode', sa.Enum('coverage_maximization', 'resource_allocation', name='optimizermode'), nullable=True),
    sa.Column('team_count', sa.Integer(), nullable=True),
    sa.Column('request_slot_count', sa.Integer(), nullable=True),
    sa.Column('assignment', sa.JSON(), nullable=False),
    sa.Column('expected_coverage_total', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('naive_baseline_coverage', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'approved', 'rejected', name='deploymentstatus'), nullable=False),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ),
    sa.PrimaryKeyConstraint('deployment_id')
    )
    op.create_table('intervention_outcomes',
    sa.Column('outcome_id', sa.String(length=36), nullable=False),
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('recorded_by', sa.String(length=36), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.Enum('cash_out_prevented', 'cash_out_occurred_elsewhere', 'no_activity', 'funds_recovered_partial', 'funds_recovered_full', name='outcomeresult'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('feeds_retraining', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['recommended_deployments.deployment_id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('outcome_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Deliberately not dropping the postgis extension here: DROP EXTENSION
    # postgis cascades into the tiger/topology schemas the postgis/postgis
    # image ships alongside it, which is destructive far beyond this
    # migration's own tables, and downgrade isn't part of the normal
    # lifecycle anyway (see docs/IMPLEMENTATION_PLAN.md's technical debt
    # entry on this migration's enum-type downgrade already being
    # incomplete on Postgres - downgrade is a known-broken path today,
    # not one this adds a new sharp edge to).
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intervention_outcomes')
    op.drop_table('recommended_deployments')
    op.drop_table('alerts')
    op.drop_table('transactions')
    op.drop_table('predictions')
    op.drop_table('feature_snapshots')
    op.drop_index(op.f('ix_linked_entities_entity_hash'), table_name='linked_entities')
    op.drop_table('linked_entities')
    op.drop_index(op.f('ix_complaints_incident_reference'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_audit_events_seq_no'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('response_units')
    op.drop_table('h3_cell_jurisdiction')
    op.drop_index(op.f('ix_accounts_ring_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_hash'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('model_registry')
    op.drop_table('jurisdictions')
    op.drop_index(op.f('ix_exit_channels_h3_cell'), table_name='exit_channels')
    op.drop_table('exit_channels')
    op.drop_table('banks')
    # ### end Alembic commands ###
