"""phase 2b: detected ring intelligence tables

Revision ID: e274d311fa2e
Revises: 31b82a0dc987
Create Date: 2026-08-26 23:27:22.041111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e274d311fa2e'
down_revision: Union[str, Sequence[str], None] = '31b82a0dc987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detected_rings',
    sa.Column('ring_id', sa.String(length=64), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('algorithm_name', sa.String(length=64), nullable=False),
    sa.Column('algorithm_version', sa.String(length=64), nullable=False),
    sa.Column('source_graph_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('average_transaction_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('transaction_velocity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fan_in_count', sa.Integer(), nullable=False),
    sa.Column('fan_out_count', sa.Integer(), nullable=False),
    sa.Column('fan_in_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('fan_out_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('ip_count', sa.Integer(), nullable=False),
    sa.Column('phone_count', sa.Integer(), nullable=False),
    sa.Column('vpa_count', sa.Integer(), nullable=False),
    sa.Column('geographic_spread_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('burst_ratio', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('cohesion_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('exit_channel_ids', sa.JSON(), nullable=False),
    sa.Column('suspiciousness_features', sa.JSON(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ring_id')
    )
    op.create_table('detected_ring_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ring_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['ring_id'], ['detected_rings.ring_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ring_id', 'account_id', name='uq_ring_member')
    )
    op.create_table('detected_ring_complaints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ring_id', sa.String(length=64), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ),
    sa.ForeignKeyConstraint(['ring_id'], ['detected_rings.ring_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ring_id', 'complaint_id', name='uq_ring_complaint')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detected_ring_complaints')
    op.drop_table('detected_ring_members')
    op.drop_table('detected_rings')
    # ### end Alembic commands ###
